### ISSUE TITLE
Quiz Printer with New Quizzes

### ISSUE THREAD

**Issue by kjmarsha** [peterfoxflick/CanvasQuizPrinter#3]
The quiz printer works very nicely with the current version of quizzes.  However Canvas has a new version of quizzes that will be taking over next school year.  It is currently accessible through the assignments screen.  These quizzes do not work on your quiz printer.  Since this platform will be replacing the old one, do you have plans to update your extension to work with new quizzes?

**Comment by peterfoxflick** [comment]
I do plan to update this extension to work with the new quizzes feature. Unfortunately, Canvas has not made the API (backend access for developers) for this feature available yet. Once the API is available I'll update the extension.
